sudo: required

services:
  - docker

before_install:
  - docker build -t hmsdt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hmsdt/react-test npm test -- --coverage

after_success:
  - docker build -t hmsdt/multi-client ./client
  - docker build -t hmsdt/multi-nginx ./nginx
  - docker build -t hmsdt/multi-server ./server
  - docker build -t hmsdt/multi-worker ./worker

  # Log in to the docker CI
  # Take those images and push them into docker-hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hmsdt/multi-client
  - docker push hmsdt/multi-nginx
  - docker push hmsdt/multi-server
  - docker push hmsdt/multi-worker


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-255510537618"
    bucket_path: "docker-multi"
    on:
      branch: master

    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"